Param(
    [Parameter(Mandatory=$false)]
    [Switch] $release,

    [Parameter(Mandatory=$false)]
    [Switch] $timing
)

$TARGET = "aarch64-linux-android"
$OutputDirectory = "$PSScriptRoot/mbf-site/public"
$AgentDetailsOutputPath = "$PSScriptRoot/mbf-site/src/agent_manifest.ts"
$OutputPath = "$OutputDirectory/mbf-agent"
$CargoManifestPath = "$PSScriptRoot/mbf-agent/Cargo.toml"

$Command = "cargo build --manifest-path $CargoManifestPath --target $TARGET"
if ( $release -eq $true )
{
    $Command += " --release"
    $Configuration = "release"
}   
else
{
    $Configuration = "debug"
}

if( $timing -eq $true )
{
    $Command += " --features request_timing"
}

Invoke-Expression $Command

$ExecutablePath = "$PSScriptRoot/target/$TARGET/$Configuration/mbf-agent"

Copy-Item $ExecutablePath $OutputPath
$SHA1Hash = Get-FileHash -Algorithm SHA1 -Path $ExecutablePath | select -ExpandProperty Hash
$Utf8NoBomEncoding = New-Object System.Text.UTF8Encoding $False
$AgentLength = (Get-Item $OutputPath).Length;
$AgentDetailsContents = @'
// THIS FILE IS AUTOMATICALLY GENERATED
// The uncompressed length of the MBF agent in bytes.
export const AGENT_LENGTH: number = 
'@ + $AgentLength + @'

// The SHA1 hash of the MBF agent, as a string base64 encoded.
export const AGENT_SHA1: string = "
'@ + $SHA1Hash + '"';

[System.IO.File]::WriteAllLines($AgentDetailsOutputPath, $AgentDetailsContents, $Utf8NoBomEncoding)
