// THIS FILE IS AUTOMATICALLY GENERATED
// The uncompressed length of the MBF agent in bytes.
export const AGENT_LENGTH: number = 22641696
// The SHA1 hash of the MBF agent, as a string base64 encoded.
export const AGENT_SHA1: string = "1452F15498342B798A141A8166E09D2BCB1F3BEB"
