$TARGET = "aarch64-linux-android"
$OutputDirectory = "$PSScriptRoot/../mbf-site/public"
$AgentDetailsOutputPath = "$PSScriptRoot/../mbf-site/src/agent_manifest.ts"
$OutputPath = "$OutputDirectory/mbf-agent"

cargo build --manifest-path $PSScriptRoot/Cargo.toml --target $TARGET --release
Copy-Item $PSScriptRoot/target/$TARGET/release/mbf-agent $OutputPath
$SHA1Hash = Get-FileHash -Algorithm SHA1 -Path $PSScriptRoot/target/$TARGET/release/mbf-agent | select -ExpandProperty Hash
$Utf8NoBomEncoding = New-Object System.Text.UTF8Encoding $False
$AgentLength = (Get-Item $OutputPath).Length;
$AgentDetailsContents = @'
// THIS FILE IS AUTOMATICALLY GENERATED
// The uncompressed length of the MBF agent in bytes.
export const AGENT_LENGTH: number = 
'@ + $AgentLength + @'

// The SHA1 hash of the MBF agent, as a string base64 encoded.
export const AGENT_SHA1: string = "
'@ + $SHA1Hash + '"';

[System.IO.File]::WriteAllLines($AgentDetailsOutputPath, $AgentDetailsContents, $Utf8NoBomEncoding)
