$Release = $args[0]

$TARGET = "aarch64-linux-android"
$OutputDirectory = "$PSScriptRoot/../mbf-site/public"
$AgentDetailsOutputPath = "$PSScriptRoot/../mbf-site/src/agent_manifest.ts"
$OutputPath = "$OutputDirectory/mbf-agent"

if ( $Release.Length -ne 0 )
{
    cargo build --manifest-path $PSScriptRoot/Cargo.toml --target $TARGET --release
    $Configuration = "release"
}   
else
{
    cargo build --manifest-path $PSScriptRoot/Cargo.toml --target $TARGET
    $Configuration = "debug"
}
$ExecutablePath = "$PSScriptRoot/target/$TARGET/$Configuration/mbf-agent"

Copy-Item $ExecutablePath $OutputPath
$SHA1Hash = Get-FileHash -Algorithm SHA1 -Path $ExecutablePath | select -ExpandProperty Hash
$Utf8NoBomEncoding = New-Object System.Text.UTF8Encoding $False
$AgentLength = (Get-Item $OutputPath).Length;
$AgentDetailsContents = @'
// THIS FILE IS AUTOMATICALLY GENERATED
// The uncompressed length of the MBF agent in bytes.
export const AGENT_LENGTH: number = 
'@ + $AgentLength + @'

// The SHA1 hash of the MBF agent, as a string base64 encoded.
export const AGENT_SHA1: string = "
'@ + $SHA1Hash + '"';

[System.IO.File]::WriteAllLines($AgentDetailsOutputPath, $AgentDetailsContents, $Utf8NoBomEncoding)
