name: "Compile and deploy"
on:
  workflow_dispatch:
  push:
    branches: ['deploy']

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      baseUrl: './'
      artifactName: mbf-site

  gh-pages:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './mbf-site/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
